/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   mbx_scancodes.h                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: daemo <daemo@student.42.fr>                +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/11/25 17:25:27 by daemo             #+#    #+#             */
/*   Updated: 2026/04/24 16:11:15 by rprieur          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#pragma once

enum	e_mbx_scancode_section
{
	MBX_SCANCODES_START				= 0,
	MBX_SCANCODES_END				= 559,
	MBX_SCANCODES_LENGTH			= 560,
	MBX_SCANCODES_KEYBOARD_START	= 0,
	MBX_SCANCODES_KEYBOARD_END		= 511,
	MBX_SCANCODES_MOUSE_START		= 512,
	MBX_SCANCODES_MOUSE_END			= 527,
	MBX_SCANCODES_WINDOW_START		= 528,
	MBX_SCANCODES_WINDOW_END		= 559
};

// Simplified version of SLD2's scancodes
// [https://wiki.libsdl.org/SDL2/SDL_Scancode]
// Mouse and Window events are put after Keyboard ones

enum	e_mbx_scancode
{
	MBX_KEY_NONE			= 0,
	MBX_KEY_A				= 4,
	MBX_KEY_B				= 5,
	MBX_KEY_C				= 6,
	MBX_KEY_D				= 7,
	MBX_KEY_E				= 8,
	MBX_KEY_F				= 9,
	MBX_KEY_G				= 10,
	MBX_KEY_H				= 11,
	MBX_KEY_I				= 12,
	MBX_KEY_J				= 13,
	MBX_KEY_K				= 14,
	MBX_KEY_L				= 15,
	MBX_KEY_M				= 16,
	MBX_KEY_N				= 17,
	MBX_KEY_O				= 18,
	MBX_KEY_P				= 19,
	MBX_KEY_Q				= 20,
	MBX_KEY_R				= 21,
	MBX_KEY_S				= 22,
	MBX_KEY_T				= 23,
	MBX_KEY_U				= 24,
	MBX_KEY_V				= 25,
	MBX_KEY_W				= 26,
	MBX_KEY_X				= 27,
	MBX_KEY_Y				= 28,
	MBX_KEY_Z				= 29,
	MBX_KEY_1				= 30,
	MBX_KEY_2				= 31,
	MBX_KEY_3				= 32,
	MBX_KEY_4				= 33,
	MBX_KEY_5				= 34,
	MBX_KEY_6				= 35,
	MBX_KEY_7				= 36,
	MBX_KEY_8				= 37,
	MBX_KEY_9				= 38,
	MBX_KEY_0				= 39,
	MBX_KEY_RETURN			= 40,
	MBX_KEY_ENTER			= 40,
	MBX_KEY_ESCAPE			= 41,
	MBX_KEY_BACKSPACE		= 42,
	MBX_KEY_TAB				= 43,
	MBX_KEY_SPACE			= 44,
	MBX_KEY_MINUS			= 45,
	MBX_KEY_EQUALS			= 46,
	MBX_KEY_LEFTBRACKET		= 47,
	MBX_KEY_RIGHTBRACKET	= 48,
	MBX_KEY_BACKSLASH		= 49,
	MBX_KEY_NONUSHASH		= 50,
	MBX_KEY_SEMICOLON		= 51,
	MBX_KEY_APOSTROPHE		= 52,
	MBX_KEY_GRAVE			= 53,
	MBX_KEY_COMMA			= 54,
	MBX_KEY_PERIOD			= 55,
	MBX_KEY_SLASH			= 56,
	MBX_KEY_CAPSLOCK		= 57,
	MBX_KEY_F1				= 58,
	MBX_KEY_F2				= 59,
	MBX_KEY_F3				= 60,
	MBX_KEY_F4				= 61,
	MBX_KEY_F5				= 62,
	MBX_KEY_F6				= 63,
	MBX_KEY_F7				= 64,
	MBX_KEY_F8				= 65,
	MBX_KEY_F9				= 66,
	MBX_KEY_F10				= 67,
	MBX_KEY_F11				= 68,
	MBX_KEY_F12				= 69,
	MBX_KEY_PRINTSCREEN		= 70,
	MBX_KEY_SCROLLLOCK		= 71,
	MBX_KEY_PAUSE			= 72,
	MBX_KEY_INSERT			= 73,
	MBX_KEY_HOME			= 74,
	MBX_KEY_PAGEUP			= 75,
	MBX_KEY_DELETE			= 76,
	MBX_KEY_END				= 77,
	MBX_KEY_PAGEDOWN		= 78,
	MBX_KEY_RIGHT			= 79,
	MBX_KEY_LEFT			= 80,
	MBX_KEY_DOWN			= 81,
	MBX_KEY_UP				= 82,
	MBX_KEY_NUMLOCKCLEAR	= 83,
	MBX_KEY_KP_DIVIDE		= 84,
	MBX_KEY_KP_MULTIPLY		= 85,
	MBX_KEY_KP_MINUS		= 86,
	MBX_KEY_KP_PLUS			= 87,
	MBX_KEY_KP_ENTER		= 88,
	MBX_KEY_KP_1			= 89,
	MBX_KEY_KP_2			= 90,
	MBX_KEY_KP_3			= 91,
	MBX_KEY_KP_4			= 92,
	MBX_KEY_KP_5			= 93,
	MBX_KEY_KP_6			= 94,
	MBX_KEY_KP_7			= 95,
	MBX_KEY_KP_8			= 96,
	MBX_KEY_KP_9			= 97,
	MBX_KEY_KP_0			= 98,
	MBX_KEY_KP_PERIOD		= 99,
	MBX_KEY_LCTRL			= 224,
	MBX_KEY_LSHIFT			= 225,
	MBX_KEY_LALT			= 226,
	MBX_KEY_LGUI			= 227,
	MBX_KEY_RCTRL			= 228,
	MBX_KEY_RSHIFT			= 229,
	MBX_KEY_RALT			= 230,
	MBX_KEY_RGUI			= 231,
	MBX_MOUSE_LEFT			= 513,
	MBX_MOUSE_MIDDLE		= 514,
	MBX_MOUSE_RIGHT			= 515,
	MBX_MOUSE_4				= 516,
	MBX_MOUSE_5				= 517,
	MBX_WINDOW_CLOSE		= 528,
	MBX_WINDOW_MOVE			= 529,
	MBX_WINDOW_MINIMIZE		= 530,
	MBX_WINDOW_MAXIMIZE		= 531,
	MBX_WINDOW_ENTER		= 532,
	MBX_WINDOW_FOCUS		= 533,
	MBX_WINDOW_LEAVE		= 534,
	MBX_WINDOW_UNFOCUS		= 535,
	MBX_WINDOW_RESIZE		= 536
};
